version: '3.7'

networks:
  matrix-network:

services:
  traefik:
    image: traefik:v2.9
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic_conf.yml:/etc/traefik/dynamic_conf.yml:ro
      - ./traefik/certs:/etc/traefik/certs:ro
    networks:
      matrix-network:
        aliases:
          - hs1
          - hs2
          - rc1

# HomeServer 1 (synapse)
  hs1:
    image: matrixdotorg/synapse:latest
    # build:
    #   context: ../synapse
    #   dockerfile: ../synapse/docker/Dockerfile
    container_name: hs1
    entrypoint: sh -c "update-ca-certificates && /start.py"
    volumes:
      - ./hs1:/data
      - ./traefik/certs/ca:/usr/local/share/ca-certificates
    networks:
      - matrix-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hs1.rule=Host(`hs1`)"
      - "traefik.http.routers.hs1.entrypoints=websecure"
      - "traefik.http.routers.hs1.tls=true"
      - "traefik.http.services.hs1.loadbalancer.server.port=8008"

# HomeServer 2 (synapse)
  hs2:
    image: matrixdotorg/synapse:latest
    container_name: hs2
    entrypoint: sh -c "update-ca-certificates && /start.py"
    volumes:
      - ./hs2:/data
      - ./traefik/certs/ca:/usr/local/share/ca-certificates
    networks:
      - matrix-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hs2.rule=Host(`hs2`)"
      - "traefik.http.routers.hs2.entrypoints=websecure"
      - "traefik.http.routers.hs2.tls=true"
      - "traefik.http.services.hs2.loadbalancer.server.port=8008"

# HomeServer 2 (synapse)
  rc1:
    build:
      context: ../homeserver
    container_name: rc1
    entrypoint: sh -c "update-ca-certificates && bun run --watch index.ts"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/rc1
    volumes:
      - ./traefik/certs/ca:/usr/local/share/ca-certificates
      - ../homeserver:/usr/src/app
    networks:
      - matrix-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rc1.rule=Host(`rc1`)"
      - "traefik.http.routers.rc1.entrypoints=websecure"
      - "traefik.http.routers.rc1.tls=true"
      - "traefik.http.services.rc1.loadbalancer.server.port=8080"

  mongo:
    image: mongo:6.0
    container_name: mongo
    volumes:
      - ./mongodb/data:/data/db
    networks:
      - matrix-network

# Element
  element:
    image: vectorim/element-web
    container_name: element
    ports:
      - "8080:80"
    volumes:
      - ./element/config.json:/app/config.json
    networks:
      - matrix-network
    depends_on:
      - hs1
      - hs2
      - rc1

