tls:
  certificates:
    # synapse1
    - certFile: "/etc/traefik/certs/hs1.pem"
      keyFile: "/etc/traefik/certs/hs1-key.pem"

    # synapse2
    - certFile: "/etc/traefik/certs/hs2.pem"
      keyFile: "/etc/traefik/certs/hs2-key.pem"

    # rocket.chat1
    - certFile: "/etc/traefik/certs/rc.host.pem"
      keyFile: "/etc/traefik/certs/rc.host-key.pem"

    # element
    - certFile: "/etc/traefik/certs/element.pem"
      keyFile: "/etc/traefik/certs/element-key.pem"

http:
  services:
    rc1:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:3000"
        passHostHeader: true

  routers:
    rc1:
      rule: "Host(`rc.host`)"
      entryPoints: ["websecure"]
      tls: true
      service: "rc1"
